# Controls when the action will run.
on:
  # Triggers the workflow on push events to the master branch.
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on (in this case, the latest version of Ubuntu).
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      - name: Connect to the SSH server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/crm.mymadinaty.com/dms_fronEnd
            git pull origin master
            git status

      - name: Debug Information
        run: |
          pwd
          ls -al

      - name: Get Node.js version
        id: node
        run: |
          echo "::set-output name=version::$(node -v)"

      - name: Cache Node.js dependencies (node_modules)
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
      
      - name: Install dependencies and build
        run: |
         cd /www/wwwroot/crm.mymadinaty.com/dms_fronEnd
         yarn install  # Install dependencies
         yarn build    # Build the project
